### PR TITLE
changes to the structure of the repository, works for single level variables

### PR DESCRIPTION
**Pull request by franzihe**
@annefou

### CODE REVIEW

**Review by annefou — CHANGES_REQUESTED** [review]
Great! Could you remove all *.pyc files? Thanks!

**Comment by franzihe** [comment]
<p>Ok, Where do I have the Research Object? Is it on ROHub or in the readme?</p>

---

 <a href='https://app.reviewnb.com/NordicESMhub/eosc-nordic-climate-demonstrator/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by annefou** [comment]
<p>You can add a resource. I would add it in input folder. Your research object is at https://w3id.org/ro-id/5c135a7b-70bf-45f3-9895-3103e0e29c11</p>

---

 <a href='https://app.reviewnb.com/NordicESMhub/eosc-nordic-climate-demonstrator/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by franzihe** [comment]
<p>Is it possible to make the python files in /work/utils as a package in /work/utils so that I don't need to append the path?</p><p> </p>

---

 <a href='https://app.reviewnb.com/NordicESMhub/eosc-nordic-climate-demonstrator/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
